name: Ratchet
on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/**'

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: ratchet lint
        run: |
          docker run --rm -v "$PWD/.github/workflows:/workflows" -w /workflows \
            ghcr.io/sethvargo/ratchet:0.12.0 \
            lint quality.yml ratchet.yml
